"""empty message

Revision ID: cff63dc2dc17
Revises: 6c369edd2a4c
Create Date: 2020-09-22 03:20:53.984545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cff63dc2dc17'
down_revision = '6c369edd2a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('campaign', sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False))
    op.alter_column('campaign', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaign', 'updated_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign', 'updated_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('campaign', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('campaign', 'is_active')
    op.drop_column('campaign', 'description')
    # ### end Alembic commands ###
